version: 2

jobs:
  deploy:
    docker:
      - image: seriousben/docker-hugo-on-github:latest
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Install and configure dependencies
          command: |
            git config user.email "ci-build@seriousben.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "2d:0a:82:60:1b:12:4f:7a:66:cf:8a:1e:5d:27:41:61"
      - run:
          name: Generate site
          command: hugo && ls public
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --message "Auto deploy" --dist public/

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: master

